services:
  redis:
    image: "redis:latest"
    volumes:
      - "./data:/data"
      - "./redis.conf:/etc/redis.conf"
    command: "/etc/redis.conf"

  chat:
    build: .
    ports:
      - 3001:3001
      - 8082:8082
    command: ruby redis_pubsub_demo.rb
    depends_on:
      - redis
